In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [4]:
from sklearn.model_selection import train_test_split
X = df.drop('species', axis = 1)
y = df['species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=7)
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [6]:
model_knn.score(X_test, y_test)

1.0

In [7]:
from sklearn.svm import SVC
model_svc = SVC(gamma='auto')

In [8]:
model_svc.fit(X_train, y_train)
model_svc.score(X_test, y_test)

1.0

now using grid search cv

In [9]:
from sklearn.model_selection import GridSearchCV
classifier = GridSearchCV(model_svc, {
    'C': [1, 10, 20, 30, 40, 50],
    'kernel': ['rbf', 'linear']
}, cv=5, return_train_score=False)

In [10]:
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30, 40, 50],
                         'kernel': ['rbf', 'linear']})

In [11]:
classifier.cv_results_

{'mean_fit_time': array([0.00314355, 0.01043673, 0.00219469, 0.00380449, 0.00214391,
        0.00185251, 0.00204988, 0.00202484, 0.0019712 , 0.0017899 ,
        0.0021091 , 0.0035964 ]),
 'std_fit_time': array([6.85977097e-04, 1.38439347e-02, 9.94547207e-05, 3.42958371e-03,
        4.02308937e-04, 1.28698429e-04, 2.64454653e-04, 2.06880482e-04,
        4.35051741e-04, 1.75645775e-04, 3.04235089e-04, 3.56773503e-03]),
 'mean_score_time': array([0.0024467 , 0.00233345, 0.00346031, 0.00177808, 0.00192528,
        0.00155668, 0.00155525, 0.00157113, 0.0014081 , 0.0013938 ,
        0.00171828, 0.00142565]),
 'std_score_time': array([0.00054199, 0.00058855, 0.00332085, 0.00056907, 0.00055929,
        0.00050907, 0.0002549 , 0.00056128, 0.00015348, 0.00042631,
        0.00032888, 0.00024292]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30, 40, 40, 50, 50],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 40, 'kernel': 'rbf'},
  {'C': 40, 'kernel': 'linear'},
  {'C': 50, 'kernel': 'rbf'},
  {'C': 50, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        , 1.        , 1.        ,
        1.        , 1.        ]),
 'split1_test_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.96666667, 1.        ,
        0.96666667, 1.        ]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       , 0.9       , 0.9       ,
        0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       , 0.93333333, 0.9       ,
        0.93333333, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      , 0.96      , 0.96      ,
        0.96      , 0.96666667]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979, 0.03887301, 0.04898979,
        0.03887301, 0.0421637 ]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 8, 8, 8, 8, 8, 6], dtype=int32)}

In [12]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003144,0.000686,0.002447,0.000542,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.010437,0.013844,0.002333,0.000589,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002195,0.000099,0.003460,0.003321,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003804,0.003430,0.001778,0.000569,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002144,0.000402,0.001925,0.000559,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.001853,0.000129,0.001557,0.000509,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002050,0.000264,0.001555,0.000255,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,8
7,0.002025,0.000207,0.001571,0.000561,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,8
8,0.001971,0.000435,0.001408,0.000153,40,rbf,"{'C': 40, 'kernel': 'rbf'}",1.000000,0.966667,0.900000,0.933333,1.0,0.960000,0.038873,8
9,0.001790,0.000176,0.001394,0.000426,40,linear,"{'C': 40, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,8
10,0.002109,0.000304,0.001718,0.000329,50,rbf,"{'C': 50, 'kernel': 'rbf'}",1.000000,0.966667,0.900000,0.933333,1.0,0.960000,0.038873,8
11,0.003596,0.003568,0.001426,0.000243,50,linear,"{'C': 50, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6

In [13]:
results[['param_C', 'param_kernel', 'mean_test_score']]

    param_C param_kernel  mean_test_score
0         1          rbf         0.980000
1         1       linear         0.980000
2        10          rbf         0.980000
3        10       linear         0.973333
4        20          rbf         0.966667
5        20       linear         0.966667
6        30          rbf         0.960000
7        30       linear         0.960000
8        40          rbf         0.960000
9        40       linear         0.960000
10       50          rbf         0.960000
11       50       linear         0.966667

In [14]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier()

In [15]:
classifier2 = GridSearchCV(model_knn, {
    'n_neighbors': [3, 5, 7, 9, 11, 13],
    'weights': ['uniform', 'distance'], 
    'metric': ['euclidean', 'manhattan']
}, cv=5, return_train_score=False)

In [16]:
classifier2.fit(X, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']})

In [17]:
print(classifier2.cv_results_.keys())

dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_metric', 'param_n_neighbors', 'param_weights', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'split3_test_score', 'split4_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score'])

In [18]:
results2 = pd.DataFrame(classifier2.cv_results_)
results2[['param_n_neighbors', 'param_weights', 'param_metric', 'mean_test_score']]

    param_n_neighbors param_weights param_metric  mean_test_score
0                   3       uniform    euclidean         0.966667
1                   3      distance    euclidean         0.966667
2                   5       uniform    euclidean         0.973333
3                   5      distance    euclidean         0.966667
4                   7       uniform    euclidean         0.980000
5                   7      distance    euclidean         0.980000
6                   9       uniform    euclidean         0.973333
7                   9      distance    euclidean         0.973333
8                  11       uniform    euclidean         0.980000
9                  11      distance    euclidean         0.986667
10                 13       uniform    euclidean         0.973333
11                 13      distance    euclidean         0.980000
12                  3       uniform    manhattan         0.960000
13                  3      distance    manhattan         0.960000
14                  5       uniform    manhattan         0.960000
15                  5      distance    manhattan         0.960000
16                  7       uniform    manhattan         0.973333
17                  7      distance    manhattan         0.960000
18                  9       uniform    manhattan         0.966667
19                  9      distance    manhattan         0.960000
20                 11       uniform    manhattan         0.980000
21                 11      distance    manhattan         0.966667
22                 13       uniform    manhattan         0.973333
23                 13      distance    manhattan         0.966667

In [19]:
from sklearn.model_selection import RandomizedSearchCV

In [20]:
classifier3 = RandomizedSearchCV(model_knn, {
    'n_neighbors': [3, 5, 7, 9, 11, 13],
    'weights': ['uniform', 'distance'], 
    'metric': ['euclidean', 'manhattan']
}, n_iter = 4, cv=5, return_train_score=False)

In [21]:
classifier3.fit(X, y)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=4,
                   param_distributions={'metric': ['euclidean', 'manhattan'],
                                        'n_neighbors': [3, 5, 7, 9, 11, 13],
                                        'weights': ['uniform', 'distance']})

In [22]:
classifier3.cv_results_

{'mean_fit_time': array([0.00275559, 0.0016758 , 0.00176778, 0.00151854]),
 'std_fit_time': array([0.00072523, 0.00038204, 0.00060414, 0.00020753]),
 'mean_score_time': array([0.00340633, 0.00209241, 0.0019628 , 0.00180244]),
 'std_score_time': array([0.000771  , 0.00062377, 0.00087984, 0.00021373]),
 'param_weights': masked_array(data=['uniform', 'distance', 'distance', 'distance'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[13, 9, 5, 7],
              mask=[False, False, False, False],
        fill_value=999999),
 'param_metric': masked_array(data=['euclidean', 'manhattan', 'manhattan', 'manhattan'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'weights': 'uniform', 'n_neighbors': 13, 'metric': 'euclidean'},
  {'weights': 'distance', 'n_neighbors': 9, 'metric': 'manhattan'},
  {'weights': 'distance', 'n_neighbors': 5, 'metric': 'manhattan'},
  {'weights': 'distance', 'n_neighbors': 7, 'metric': 'manhattan'}],
 'split0_test_score': array([0.93333333, 0.96666667, 0.96666667, 0.96666667]),
 'split1_test_score': array([1.        , 0.96666667, 0.96666667, 0.96666667]),
 'split2_test_score': array([0.96666667, 0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1.]),
 'mean_test_score': array([0.97333333, 0.96      , 0.96      , 0.96      ]),
 'std_test_score': array([0.02494438, 0.03265986, 0.03265986, 0.03265986]),
 'rank_test_score': array([1, 2, 2, 2], dtype=int32)}

In [23]:
res_random = pd.DataFrame(classifier3.cv_results_)
res_random[['param_n_neighbors', 'param_weights', 'param_metric', 'mean_test_score']]

   param_n_neighbors param_weights param_metric  mean_test_score
0                 13       uniform    euclidean         0.973333
1                  9      distance    manhattan         0.960000
2                  5      distance    manhattan         0.960000
3                  7      distance    manhattan         0.960000

ensemble learning-

stacking

In [24]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size = 0.3, random_state = 42, stratify=y_encoded)

# setosa- 0, versicolor- 1, virginica- 2

In [26]:
base_models = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svm', SVC(probability=True, gamma='auto', C=10, kernel='rbf', random_state=42)),
    ('lr', LogisticRegression(random_state=42, max_iter=1000))
]

In [ ]:
meta_model = RandomizedSearchCV(model_knn, {
    'n_neighbors': [3, 5, 7, 9, 11, 13, 15],
    'weights': ['uniform', 'distance'], 
    'metric': ['euclidean', 'manhattan']
}, n_iter = 4, cv=5, return_train_score=False)
meta_model.fit(X_train, y_train)  # n = 11 is the best

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=4,
                   param_distributions={'metric': ['euclidean', 'manhattan'],
                                        'n_neighbors': [3, 5, 7, 9, 11, 13, 15],
                                        'weights': ['uniform', 'distance']})

In [36]:
y_pred_meta = meta_model.predict(X_test)
accuracy_meta = accuracy_score(y_test, y_pred_meta)
print(f"Meta model accuracy: {accuracy_meta:.4f}")

Meta model accuracy: 0.9333

In [37]:
stacking_classifier = StackingClassifier(estimators=base_models, final_estimator=meta_model, cv=5)

In [38]:
stacking_classifier.fit(X_train, y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svm',
                                SVC(C=10, gamma='auto', probability=True,
                                    random_state=42)),
                               ('lr',
                                LogisticRegression(max_iter=1000,
                                                   random_state=42))],
                   final_estimator=RandomizedSearchCV(cv=5,
                                                      estimator=KNeighborsClassifier(),
                                                      n_iter=4,
                                                      param_distributions={'metric': ['euclidean',
                                                                                      'manhattan'],
                                                                           'n_neighbors': [3,
                                                                                           5,
                                                                                           7,
                                                                                           9,
                                                                                           11,
                                                                                           13,
                                                                                           15],
                                                                           'weights': ['uniform',
                                                                                       'distance']}))

In [39]:
y_pred = stacking_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9555555555555556

bagging

random forest

In [40]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(n_estimators=100,  # no. of trees
                                  max_depth=None,  # max depth of each tree. here None. we let them grow fully.
                                  random_state=42)

In [41]:
model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
accuracy_rf

0.8888888888888888

boosting

adaboost
- use when underfitting
- i.e when high bias, high variance.. when the model doesnt perform well on both training n testing data.

In [42]:
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier
from xgboost import XGBClassifier

In [43]:
ada_model = AdaBoostClassifier(n_estimators=100, random_state=42)
ada_model.fit(X_train, y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [44]:
y_pred_ada = ada_model.predict(X_test)
accuracy_ada = accuracy_score(y_test, y_pred_ada)
accuracy_ada

0.9333333333333333

gradient boosting

In [45]:
gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)
gb_model.fit(X_train, y_train)

GradientBoostingClassifier(random_state=42)

In [46]:
y_pred_gb = gb_model.predict(X_test)
accuracy_gb = accuracy_score(y_test, y_pred_gb)
accuracy_gb

0.9333333333333333

In [47]:
xgb_model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth = 3, random_state=42, use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_train, y_train)

c:\Users\Mrunmayee Potdar\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [09:28:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [48]:
y_pred_xgb = xgb_model.predict(X_test)
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)   
accuracy_xgb

0.9333333333333333

use bagging for underfitting, boosting for overfitting